services:
  imap-dovecot:
    container_name: imap-dovecot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TIMEZONE: ${TIMEZONE}
      PASSKEY: ${PASSKEY}
      IMAP_SERVER: ${IMAP_SERVER}
    init: true
    cap_add:
      - CAP_SETGID
      - CAP_SETUID
    user: serviceuser
    group_add:
      - users
      - dovecot
      - dovenull
      - fetchmail
      - spamd
      - clamav
      - unbound
    volumes:
      - ./conf/dovecot:/etc/dovecot
      - ./conf/fetchmail/fetchmailrc_template:/opt/fetchmail/fetchmailrc_template:ro
      - ./conf/resolv/resolv.conf:/etc/resolv.conf:ro
      - ./conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./conf/sieve/default.sieve:/opt/sieve/default.sieve:ro
      - ./conf/spamassassin/local.cf:/etc/spamassassin/local.cf
      - ./scripts/start:/usr/local/bin/start:ro
      - ./scripts/fetchmultimail:/usr/local/bin/fetchmultimail:ro
      - ./scripts/mda:/usr/local/bin/mda:ro
      - ./scripts/dovecot-auth:/usr/local/bin/dovecot-auth:ro
      - ./scripts/make-user:/usr/local/bin/make-user:ro
      - ./scripts/sa-learn:/usr/local/bin/sa-learn:ro
      - mail-dovecot-lib-clamav:/var/lib/clamav
      - mail-dovecot-lib-spamassassin:/var/lib/spamassassin
      - mail-dovecot-lib-dovecot:/var/lib/dovecot
      - mail-dovecot-conf-unbound:/etc/unbound
      - mail-dovecot-conf-sieve:/opt/sieve
      - mail-dovecot-conf-users:/opt/users
      - mail-dovecot-conf-ssl:/etc/ssl
      - mail-dovecot-conf-spamassassin:/etc/mail/spamassassin
      - mail-dovecot-spamassassin:/home/serviceuser/.spamassassin
      - mail-dovecot-log:/var/log
      - ${DIR_MAIL_DOVECOT}:/var/mail
      - ${DIR_LETSENCRYPT}:/etc/letsencrypt:ro
    ports:
      - 993:993
      - 4190:4190
    restart: unless-stopped
    labels:
      # Update CA Certs
      deck-chores.dovecot-update-ca-certs.cron: "0 0 0"
      deck-chores.dovecot-update-ca-certs.command: sudo update-ca-trust
      # Update ClamAV DB
      deck-chores.dovecot-update-clamav.cron: "0 0 0"
      deck-chores.dovecot-update-clamav.command: sudo freshclam --daemon-notify=/dev/null
      # Update Spamassassin rules from remote sources
      deck-chores.dovecot-spamassassin-update.cron: "0 0 0"
      deck-chores.dovecot-spamassassin-update.command: sudo /usr/bin/vendor_perl/sa-update -D
      # Update Spamassassin rules via learning
      deck-chores.dovecot-spamassassin-learn.cron: "0 0 0 15"
      deck-chores.dovecot-spamassassin-learn.command: sa-learn

volumes:
  mail-dovecot-lib-clamav:
    driver: local
  mail-dovecot-lib-spamassassin:
    driver: local
  mail-dovecot-lib-dovecot:
    driver: local
  mail-dovecot-conf-unbound:
    driver: local
  mail-dovecot-conf-sieve:
    driver: local
  mail-dovecot-conf-users:
    driver: local
  mail-dovecot-conf-ssl:
    driver: local
  mail-dovecot-conf-spamassassin:
    driver: local
  mail-dovecot-spamassassin:
    driver: local
  mail-dovecot-log:
    driver: local
  mail-dovecot-ssl:
    driver: local
